//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigma.Domain.Validation.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FertilizanteReqMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FertilizanteReqMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigma.Domain.Validation.Messages.FertilizanteReqMessage", typeof(FertilizanteReqMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo b é obrigatório. .
        /// </summary>
        internal static string b {
            get {
                return ResourceManager.GetString("b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ca é obrigatório. .
        /// </summary>
        internal static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo co é obrigatório. .
        /// </summary>
        internal static string co {
            get {
                return ResourceManager.GetString("co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo cu é obrigatório. .
        /// </summary>
        internal static string cu {
            get {
                return ResourceManager.GetString("cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo custo é obrigatório. .
        /// </summary>
        internal static string custo {
            get {
                return ResourceManager.GetString("custo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo daedap é obrigatório. .
        /// </summary>
        internal static string daedap {
            get {
                return ResourceManager.GetString("daedap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo densidade é obrigatório. .
        /// </summary>
        internal static string densidade {
            get {
                return ResourceManager.GetString("densidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo eficiencia é obrigatório. .
        /// </summary>
        internal static string eficiencia {
            get {
                return ResourceManager.GetString("eficiencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo foliar é obrigatório. .
        /// </summary>
        internal static string foliar {
            get {
                return ResourceManager.GetString("foliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo IDCicloProducao é obrigatório. .
        /// </summary>
        internal static string IDCicloProducao {
            get {
                return ResourceManager.GetString("IDCicloProducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo k2o é obrigatório. .
        /// </summary>
        internal static string k2o {
            get {
                return ResourceManager.GetString("k2o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo marcado é obrigatório. .
        /// </summary>
        internal static string marcado {
            get {
                return ResourceManager.GetString("marcado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo mg é obrigatório .
        /// </summary>
        internal static string mg {
            get {
                return ResourceManager.GetString("mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo mn é obrigatório. .
        /// </summary>
        internal static string mn {
            get {
                return ResourceManager.GetString("mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo mo é obrigatório. .
        /// </summary>
        internal static string mo {
            get {
                return ResourceManager.GetString("mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo n é obrigatório. .
        /// </summary>
        internal static string n {
            get {
                return ResourceManager.GetString("n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo nome é obrigatório. .
        /// </summary>
        internal static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo objID é obrigatório. .
        /// </summary>
        internal static string objID {
            get {
                return ResourceManager.GetString("objID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo opcao é obrigatório. .
        /// </summary>
        internal static string opcao {
            get {
                return ResourceManager.GetString("opcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo opcaoMarcado é obrigatório. .
        /// </summary>
        internal static string opcaoMarcada {
            get {
                return ResourceManager.GetString("opcaoMarcada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo p2o5 é obrigatório. .
        /// </summary>
        internal static string p2o5 {
            get {
                return ResourceManager.GetString("p2o5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo qtde é obrigatório. .
        /// </summary>
        internal static string qtde {
            get {
                return ResourceManager.GetString("qtde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo s é obrigatório. .
        /// </summary>
        internal static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo zn é obrigatório. .
        /// </summary>
        internal static string zn {
            get {
                return ResourceManager.GetString("zn", resourceCulture);
            }
        }
    }
}
