//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigma.Domain.Validation.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SequenciaImportacaoReqMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SequenciaImportacaoReqMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigma.Domain.Validation.Messages.SequenciaImportacaoReqMessage", typeof(SequenciaImportacaoReqMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Al é obrigatório. .
        /// </summary>
        internal static string Al {
            get {
                return ResourceManager.GetString("Al", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo area é obrigatório. .
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Argila é obrigatório. .
        /// </summary>
        internal static string Argila {
            get {
                return ResourceManager.GetString("Argila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo B é obrigatório. .
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Ca é obrigatório. .
        /// </summary>
        internal static string Ca {
            get {
                return ResourceManager.GetString("Ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Co é obrigatório. .
        /// </summary>
        internal static string Co {
            get {
                return ResourceManager.GetString("Co", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Compac é obrigatório. .
        /// </summary>
        internal static string Compac {
            get {
                return ResourceManager.GetString("Compac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo CTC é obrigatório. .
        /// </summary>
        internal static string CTC {
            get {
                return ResourceManager.GetString("CTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Cu é obrigatório. .
        /// </summary>
        internal static string Cu {
            get {
                return ResourceManager.GetString("Cu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Fe é obrigatório. .
        /// </summary>
        internal static string Fe {
            get {
                return ResourceManager.GetString("Fe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo IDSafra é obrigatório. .
        /// </summary>
        internal static string IDSafra {
            get {
                return ResourceManager.GetString("IDSafra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo K é obrigatório. .
        /// </summary>
        internal static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Mg é obrigatório. .
        /// </summary>
        internal static string Mg {
            get {
                return ResourceManager.GetString("Mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo Mn é obrigatório. .
        /// </summary>
        internal static string Mn {
            get {
                return ResourceManager.GetString("Mn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo MO é obrigatório. .
        /// </summary>
        internal static string MO {
            get {
                return ResourceManager.GetString("MO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo momicro é obrigatório. .
        /// </summary>
        internal static string Momicro {
            get {
                return ResourceManager.GetString("Momicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo nome é obrigatório. .
        /// </summary>
        internal static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo NomeLaboratorio é obrigatório. .
        /// </summary>
        internal static string NomeLaboratorio {
            get {
                return ResourceManager.GetString("NomeLaboratorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo NPonto é obrigatório. .
        /// </summary>
        internal static string NPonto {
            get {
                return ResourceManager.GetString("NPonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo objID é obrigatório. .
        /// </summary>
        internal static string objID {
            get {
                return ResourceManager.GetString("objID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo PHCaCl2 é obrigatório. .
        /// </summary>
        internal static string PHCaCl2 {
            get {
                return ResourceManager.GetString("PHCaCl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo PMeHl é obrigatório. .
        /// </summary>
        internal static string PMeHl {
            get {
                return ResourceManager.GetString("PMeHl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo PRes é obrigatório. .
        /// </summary>
        internal static string PRes {
            get {
                return ResourceManager.GetString("PRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo S é obrigatório. .
        /// </summary>
        internal static string S {
            get {
                return ResourceManager.GetString("S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo TpSolo é obrigatório. .
        /// </summary>
        internal static string TpSolo {
            get {
                return ResourceManager.GetString("TpSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umal é obrigatório. .
        /// </summary>
        internal static string umal {
            get {
                return ResourceManager.GetString("umal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umargila é obrigatório. .
        /// </summary>
        internal static string umargila {
            get {
                return ResourceManager.GetString("umargila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umb é obrigatório. .
        /// </summary>
        internal static string umb {
            get {
                return ResourceManager.GetString("umb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umca é obrigatório. .
        /// </summary>
        internal static string umca {
            get {
                return ResourceManager.GetString("umca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umco é obrigatório. .
        /// </summary>
        internal static string umco {
            get {
                return ResourceManager.GetString("umco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ummc é obrigatório. .
        /// </summary>
        internal static string umctc {
            get {
                return ResourceManager.GetString("umctc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umcu é obrigatório. .
        /// </summary>
        internal static string umcu {
            get {
                return ResourceManager.GetString("umcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umfe  é obrigatório. .
        /// </summary>
        internal static string umfe {
            get {
                return ResourceManager.GetString("umfe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umk2o é obrigatório. .
        /// </summary>
        internal static string umk2o {
            get {
                return ResourceManager.GetString("umk2o", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ummg é obrigatório. .
        /// </summary>
        internal static string ummg {
            get {
                return ResourceManager.GetString("ummg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ummn é obrigatório. .
        /// </summary>
        internal static string ummn {
            get {
                return ResourceManager.GetString("ummn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ummo é obrigatório. .
        /// </summary>
        internal static string ummo {
            get {
                return ResourceManager.GetString("ummo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ummomicro é obrigatório. .
        /// </summary>
        internal static string ummomicro {
            get {
                return ResourceManager.GetString("ummomicro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umphcacl2 é obrigatório. .
        /// </summary>
        internal static string umphcacl2 {
            get {
                return ResourceManager.GetString("umphcacl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umpmehl é obrigatório. .
        /// </summary>
        internal static string umpmehl {
            get {
                return ResourceManager.GetString("umpmehl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umpres é obrigatório. .
        /// </summary>
        internal static string umpres {
            get {
                return ResourceManager.GetString("umpres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo ums é obrigatório. .
        /// </summary>
        internal static string ums {
            get {
                return ResourceManager.GetString("ums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo umzn é obrigatório. .
        /// </summary>
        internal static string umzn {
            get {
                return ResourceManager.GetString("umzn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo zn é obrigatório. .
        /// </summary>
        internal static string Zn {
            get {
                return ResourceManager.GetString("Zn", resourceCulture);
            }
        }
    }
}
