//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigma.Domain.Validation.Messages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimulacaoReqMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimulacaoReqMessage() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sigma.Domain.Validation.Messages.SimulacaoReqMessage", typeof(SimulacaoReqMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo aplicouCorretivoAcidezSuperf é obrigatório. .
        /// </summary>
        internal static string aplicouCorretivoAcidezSuperf {
            get {
                return ResourceManager.GetString("aplicouCorretivoAcidezSuperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo baseFosforo é obrigatório. .
        /// </summary>
        internal static string baseFosforo {
            get {
                return ResourceManager.GetString("baseFosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo considerarResteva é obrigatório. .
        /// </summary>
        internal static string considerarResteva {
            get {
                return ResourceManager.GetString("considerarResteva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo corrigirPerfilAcidezSuperf é obrigatório. .
        /// </summary>
        internal static string corrigirPerfilAcidezSuperf {
            get {
                return ResourceManager.GetString("corrigirPerfilAcidezSuperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo corrigirPerfilEnxofre é obrigatório. .
        /// </summary>
        internal static string corrigirPerfilEnxofre {
            get {
                return ResourceManager.GetString("corrigirPerfilEnxofre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo dataPlantioFert é obrigatório. .
        /// </summary>
        internal static string dataPlantioFert {
            get {
                return ResourceManager.GetString("dataPlantioFert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo dateINC é obrigatório. .
        /// </summary>
        internal static string dateINC {
            get {
                return ResourceManager.GetString("dateINC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseMediaEnxofre é obrigatório. .
        /// </summary>
        internal static string doseMediaEnxofre {
            get {
                return ResourceManager.GetString("doseMediaEnxofre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseMediaFosforo é obrigatório. .
        /// </summary>
        internal static string doseMediaFosforo {
            get {
                return ResourceManager.GetString("doseMediaFosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseMediaPotassio é obrigatório..
        /// </summary>
        internal static string doseMediaPotassio {
            get {
                return ResourceManager.GetString("doseMediaPotassio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseZeroAcidezSuperf é obrigatório. .
        /// </summary>
        internal static string doseZeroAcidezSuperf {
            get {
                return ResourceManager.GetString("doseZeroAcidezSuperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseZeroEnxofre é obrigatório. .
        /// </summary>
        internal static string doseZeroEnxofre {
            get {
                return ResourceManager.GetString("doseZeroEnxofre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseZeroFosforo é obrigatório. .
        /// </summary>
        internal static string doseZeroFosforo {
            get {
                return ResourceManager.GetString("doseZeroFosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo doseZeroPotassio é obrigatório. .
        /// </summary>
        internal static string doseZeroPotassio {
            get {
                return ResourceManager.GetString("doseZeroPotassio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo enxofreDesejado é obrigatório. .
        /// </summary>
        internal static string enxofreDesejado {
            get {
                return ResourceManager.GetString("enxofreDesejado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo fosforoDesejado é obrigatório. .
        /// </summary>
        internal static string fosforoDesejado {
            get {
                return ResourceManager.GetString("fosforoDesejado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo IDAreaServico é obrigatório. .
        /// </summary>
        internal static string IDAreaServico {
            get {
                return ResourceManager.GetString("IDAreaServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo IDProximaCultura é obrigatório. .
        /// </summary>
        internal static string IDProximaCultura {
            get {
                return ResourceManager.GetString("IDProximaCultura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo IDUltimaCultura é obrigatório. .
        /// </summary>
        internal static string IDUltimaCultura {
            get {
                return ResourceManager.GetString("IDUltimaCultura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo IDUsuarioINC é obrigatório. .
        /// </summary>
        internal static string IDUsuarioINC {
            get {
                return ResourceManager.GetString("IDUsuarioINC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo metodoAcidezSuperficie é obrigatório. .
        /// </summary>
        internal static string metodoAcidezSuperficie {
            get {
                return ResourceManager.GetString("metodoAcidezSuperficie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo metodoEnxofre é obrigatório. .
        /// </summary>
        internal static string metodoEnxofre {
            get {
                return ResourceManager.GetString("metodoEnxofre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo metodoFosforo é obrigatório. .
        /// </summary>
        internal static string metodoFosforo {
            get {
                return ResourceManager.GetString("metodoFosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo metodoPotassio é obrigatório. .
        /// </summary>
        internal static string metodoPotassio {
            get {
                return ResourceManager.GetString("metodoPotassio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo mgMinimoAcidezSuperf é obrigatório. .
        /// </summary>
        internal static string mgMinimoAcidezSuperf {
            get {
                return ResourceManager.GetString("mgMinimoAcidezSuperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo nematoideCisto é obrigatório. .
        /// </summary>
        internal static string nematoideCisto {
            get {
                return ResourceManager.GetString("nematoideCisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo objID é obrigatório. .
        /// </summary>
        internal static string objID {
            get {
                return ResourceManager.GetString("objID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo opcao é obrigatório. .
        /// </summary>
        internal static string opcao {
            get {
                return ResourceManager.GetString("opcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo paramRecomendFert é obrigatório. .
        /// </summary>
        internal static string paramRecomendFert {
            get {
                return ResourceManager.GetString("paramRecomendFert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo perVacidezPerfil é obrigatório. .
        /// </summary>
        internal static string perVacidezPerfil {
            get {
                return ResourceManager.GetString("perVacidezPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo perVMinimoAcidezSuperf é obrigatório. .
        /// </summary>
        internal static string perVMinimoAcidezSuperf {
            get {
                return ResourceManager.GetString("perVMinimoAcidezSuperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo potassioDesejado é obrigatório. .
        /// </summary>
        internal static string potassioDesejado {
            get {
                return ResourceManager.GetString("potassioDesejado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo produtividadeFert é obrigatório. .
        /// </summary>
        internal static string produtividadeFert {
            get {
                return ResourceManager.GetString("produtividadeFert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo profundidadeAcidezPerfil é obrigatório. .
        /// </summary>
        internal static string profundidadeAcidezPerfil {
            get {
                return ResourceManager.GetString("profundidadeAcidezPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo profundidadeAcidezSuperf é obrigatório. .
        /// </summary>
        internal static string profundidadeAcidezSuperf {
            get {
                return ResourceManager.GetString("profundidadeAcidezSuperf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo utilizarCalcario é obrigatório. .
        /// </summary>
        internal static string utilizarCalcario {
            get {
                return ResourceManager.GetString("utilizarCalcario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo utilizarCorretivoAcidezPerfil é obrigatório. .
        /// </summary>
        internal static string utilizarCorretivoAcidezPerfil {
            get {
                return ResourceManager.GetString("utilizarCorretivoAcidezPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo utilizarFosforo é obrigatório. .
        /// </summary>
        internal static string utilizarFosforo {
            get {
                return ResourceManager.GetString("utilizarFosforo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Campo utilizarGesso é obrigatório. .
        /// </summary>
        internal static string utilizarGesso {
            get {
                return ResourceManager.GetString("utilizarGesso", resourceCulture);
            }
        }
    }
}
